blank_issues_enabled: false
contact_links:
  - name: StackOverflow
    url: https://stackoverflow.com/search?tab=newest&q=schemacrawler
    about: Please ask and answer questions on StackOverflow
  - name: SchemaCrawler on Katacoda
    url: https://www.katacoda.com/schemacrawler
    about: Learn how to use the SchemaCrawler command-line with live tutorials
  - name: SchemaCrawler
    url: https://www.schemacrawler.com/
    about: Review SchemaCrawler documentation
