name: CI for Project

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install packages
      run: sudo apt-get update; sudo apt-get install graphviz
    - name: Build with Maven
      env:
        TZ: GMT
      run: mvn -Dlightdb -Dheavydb -f schemacrawler-parent/pom.xml clean package jacoco:report coveralls:report
    - name: Upload coverage reports
      run: bash <(curl -s https://codecov.io/bash) -t 4456b669-238d-485f-a64a-250449710514
