name: Lint Code Base

on:
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:

      - id: checkout-code
        name: Checkout Code
        uses: actions/checkout@v2

      - id: lint-code-base
        name: Lint Code Base
        uses: docker://github/super-linter:v2.2.2
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_XML: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_PYTHON: true
          VALIDATE_RUBY: false
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_DOCKER: true
          VALIDATE_CSS: true
          VALIDATE_ENV: true
