name: Create Release

on:
  create:
    tags:
      - 'v*'
      - 'w*'

jobs:
  build:

# BUILD FOR DISTRIBUTION
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v1
    - id: setup-jdk
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - id: install-packages
      name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install graphviz -qq
    - id: prepare-tag
      name: Prepare tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_NAME="${GITHUB_REF##refs/tags/}"
        echo "::set-output name=tag_name::${TAG_NAME}"
        echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"
    - id: show-environment
      name: Show environment
      run: |
        echo ${{ toJson(runner) }}
        echo ${{ toJson(env) }}
        echo ${{ toJson(github) }}
        mvn -v
    - id: build
      name: Build
      env:
        TZ: GMT
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Ddistrib \
          clean install

# CREATE GITHUB RELEASE AND ADD ASSETS
    - id: create-release
      name: Create GitHub Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: DEBUG Release ${{ github.ref }}
        body: |
          ${{ github.sha }}
        draft: false
        prerelease: true
    - name: Upload SchemaCrawler Distribution Zip
      id: upload-release-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./schemacrawler-distrib/target/schemacrawler-16.6.1-distribution.zip
        asset_name: schemacrawler-16.6.1-distribution.zip
        asset_content_type: application/zip
    - name: Upload SchemaCrawler Distribution SHA
      id: upload-release-sha
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./schemacrawler-distrib/target/schemacrawler-16.6.1-distribution.zip.SHA-512
        asset_name: schemacrawler-16.6.1-distribution.zip.SHA-512
        asset_content_type: text/plain

# PUBLISH WEBSITE TO GITHUB PAGES
    - name: Publish Website to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./schemacrawler-distrib/target/_website
        force_orphan: true
        user_name: 'Sualeh Fatehi'
        user_email: 'sualeh@hotmail.com'
        commit_message: 'SchemaCrawler Website [${{ steps.prepare-tag.outputs.tag_name }}]'
