name: Create Release

on:
  create:
    tags:
      - 'v*'
      - 'w*'

jobs:
  build:

# BUILD FOR DISTRIBUTION
    name: Distribution build
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v1
    - id: setup-jdk
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - id: install-packages
      name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install graphviz -qq
    - id: show-environment
      name: Show environment
      run: |
        echo github.repository: ${{ github.repository }}
        echo github.ref: ${{ github.head_ref || github.ref }}
        echo github.sha: ${{ github.sha }}
        mvn -v
    - id: build
      name: Build
      env:
        TZ: GMT
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Ddistrib \
          clean install

# CREATE GITHUB RELEASE
    - id: create-release
      name: Create GitHub Release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: DEBUG Release ${{ github.ref }}
        body: |
          ${{ github.sha }}
        draft: false
        prerelease: true
    - name: Upload SchemaCrawler Distribution Zip
      id: upload-release-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./schemacrawler-distrib/target/schemacrawler-16.6.1-distribution.zip
        asset_name: schemacrawler-16.6.1-distribution.zip
        asset_content_type: application/zip
    - name: Upload SchemaCrawler Distribution SHA
      id: upload-release-sha
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./schemacrawler-distrib/target/schemacrawler-16.6.1-distribution.SHA-512
        asset_name: schemacrawler-16.6.1-distribution.SHA-512
        asset_content_type: text/plain
